-- Initial schema baseline (existing tables)
-- IF NOT EXISTS guards make this safe to run on the already-migrated remote DB

CREATE TABLE IF NOT EXISTS public.rooms (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone not null default now(),
  name        text,
  room        jsonb
);

CREATE TABLE IF NOT EXISTS public.objects (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone not null default now(),
  name        text,
  type        text,
  category    text,
  data        jsonb
);

CREATE TABLE IF NOT EXISTS public.user (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone not null default now(),
  name        text,
  room_id     bigint references public.rooms(id)
);
